main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path('go-back/', views.go_back_view, name='go_back'),
    path('setting/', views.setting_page, name='setting_page'),
]

record/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = "runres"

urlpatterns = [
    path("resister/", views.runres, name="runres"),
    path('recordres/', views.recordres, name='recordres'),
    path('recordview/<str:pk>/', views.recordview, name='recordview'),
    path('recordUpdateView/<str:pk>/<str:record_id>', views.recordUpdateView, name='recordUpdateView'),
    path('recordUpdate/<str:pk>/<str:record_id>', views.recordUpdate, name='recordUpdate'),
    path('recordrank/', views.recordRank, name="recordRank"),
    path('recordCheck/', views.recordCheck, name="recordCheck"),
    path('recordConfirm/<str:id>', views.recordConfirm, name="recordConfirm"),
    path('recordReject/<str:id>', views.recordReject, name="recordReject"),
    path('recordDelete/<str:id>', views.recordDelete, name="recordDelete"),
    path('pbrank/', views.pbRank, name="pbRank"),
    path('pbview/<str:pk>/', views.pbView, name="pbView"),
    path('pbresPage/<str:pk>/<str:category>/', views.pbresPage, name="pbresPage"),
    path('pbRes/<str:pk>/<str:category>/', views.pbRes, name="pbRes"),
    path('pbUpdateView/<str:pk>/<str:category>/', views.pbUpdateView, name="pbUpdateView"),
    path('pbUpdate/<str:pk>/<str:category>/', views.pbUpdate, name="pbUpdate"),
    path('runPbCheck/', views.runPbCheck, name="runPbCheck"),
    path('pbConfirm/<str:id>', views.pbConfirm, name="pbConfirm"),
    path('pbReject/<str:id>', views.pbReject, name="pbReject"),
    path('pbDelete/<str:id>', views.pbDelete, name="pbDelete"),
    path('teamassign/', views.team_assign_view, name="team_assign_view"),
    path("teams/assign/save/", views.save_team_members, name="save_team_members"),
]

steruncomm/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path('users/', include('users.urls')),
    path("attendance/", include("attendance.urls")),
    path("runres/", include("record.urls")),
    path("bingo/", include("bingo.urls")),
    path("article/", include("article.urls")),
    path("marathon/", include("marathon.urls")),
    path('summernote/', include('django_summernote.urls')),  # summernote URL 추가
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import *

app_name = "users"
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name = "users/login.html"), name = "login"),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
]

record/models.py
from django.conf import settings
from django.db import models
from django_resized import ResizedImageField
from multiselectfield import MultiSelectField
from django.db.models import UniqueConstraint

# def image_upload_path(instance, filename):
#    time = timezone.now()
#    return f"{instance}/{time}+{filename}"

class Team(models.Model):
    STATUS_CHOICES = [
        ('ready', '준비중'),
        ('go', '운영중'),
        ('stop', '완료'),
    ]
    team_id = models.AutoField(primary_key=True)
    team_name = models.CharField(max_length=50, null=False, blank=False)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default='ready')
    def __str__(self):
        return str(self.team_name)
    
class TeamMember(models.Model):
    member_id = models.AutoField(primary_key=True)
    team = models.ForeignKey(Team, null=True, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    leader = models.BooleanField(default=False)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user'], name='uunique_user_only_one_team')
        ]

    def __str__(self):
        return str(self.team)+"_"+str(self.user)

class Record(models.Model):
    record_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    team = models.ForeignKey(Team, null=True, blank=True, on_delete=models.SET_NULL)
    record_date = models.DateField(blank=True, null=True)
    image = ResizedImageField(size=[500,500], upload_to="record", blank=False)
    distance = models.DecimalField(max_digits=6, decimal_places=2, blank=False, null=False)
    pace_m = models.IntegerField(null=True, blank=True)
    pace_s = models.IntegerField(null=True, blank=True)
    time_h = models.IntegerField(null=True, blank=True)
    time_m = models.IntegerField(null=True, blank=True)
    time_s = models.IntegerField(null=True, blank=True)
    desc = models.TextField(blank=True)
    confirmed = models.BooleanField(default=False)

    def delete(self, *args, **kwargs):
        # 실제 파일 삭제
        if self.image:
            self.image.delete(save=False)
        # DB 데이터 삭제
        super().delete(*args, **kwargs)

    def __str__(self):
        return str(self.team)+ "_" + str(self.confirmed)+ "_" + str(self.user) + "_" + str(self.record_date) + "_" + (str(self.title))


class PersonalRecord(models.Model):
    STATUS_CHOICES = [
        ('pending', '심사중'),
        ('verified', '인증됨'),
        ('rejected', '반려됨'),
    ]
    CATEGORY_CHOICES = [
        ('10K', '10km'),
        ('HM', '하프마라톤'),
        ('FM', '풀마라톤'),
    ]
    event_name = models.CharField(max_length=50)
    runner = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    category = models.CharField(max_length=5, choices=CATEGORY_CHOICES)
    date = models.DateField(blank=True, null=True)
    record = models.DurationField()  # 시간 기록
    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default='pending'
    )
    evidence_url = ResizedImageField(size=[500,500], upload_to="record", blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    desc = models.TextField(blank=True)

    def delete(self, *args, **kwargs):
        # 실제 파일 삭제
        if self.evidence_url:
            self.evidence_url.delete(save=False)
        # DB 데이터 삭제
        super().delete(*args, **kwargs)

    class Meta:
        constraints = [
            UniqueConstraint(fields=['runner', 'category'], name='unique_user_category')
        ]

    def __str__(self):
        return f"{self.runner} - {self.category}: {self.record}"

record/views.py
from datetime import timedelta
from django.shortcuts import redirect, render
from django.db.models import Sum
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.contrib.auth.models import User

from record.models import *

# Create your views here.

def runres(request):
    pk = request.user.id
    team_list = Team.objects.all()
    my_team = TeamMember.objects.filter(user=pk)
    return render(request,"record/run_res.html", {"team_list":team_list,"my_team":my_team})

def recordres(request):
    pk = request.user.id
    team_id = request.POST.get("team")
    print(team_id)
    if request.method == "POST":
        record = Record()
        record.title = request.POST["title"]
        record.team = Team.objects.filter(team_id=team_id).first() if team_id else None
        record.user = request.user
        record.record_date = request.POST["record_date"]
        record.image = request.FILES["image"]
        record.distance = request.POST["distance"]
        record.pace_m = request.POST["pace_m"]
        record.pace_s = request.POST["pace_s"]
        if request.POST["time_h"] == '':
            record.time_h = None
        else:
            record.time_h = request.POST["time_h"]
        record.time_m = request.POST["time_m"]
        record.time_s = request.POST["time_s"]
        record.desc = request.POST["desc"]
        record.save()
        return redirect("runres:recordview",pk=pk)
    else:
        return redirect("runres:recordview",pk=pk)

def recordview(request,pk):

    month = request.GET.get('month')

    if month =="0" or month == None:
        month = "0"
        record_list = Record.objects.filter(user=pk).order_by('-record_date')
        distance_sum = Record.objects.filter(confirmed=True).filter(user=pk).aggregate(Sum('distance'))
        distance_sum_not = Record.objects.filter(user=pk).aggregate(Sum('distance'))
        
    else:
        record_list = Record.objects.filter(user=pk).filter(record_date__month=month).order_by('-record_date')
        distance_sum = Record.objects.filter(confirmed=True).filter(user=pk).filter(record_date__month=month).aggregate(Sum('distance'))
        distance_sum_not = Record.objects.filter(user=pk).filter(record_date__month=month).aggregate(Sum('distance'))
    
    page = int(request.GET.get('p', 1)) #없으면 1로 지정
    paginator = Paginator(record_list, 3) #한 페이지 당 몇개 씩 보여줄 지 지정
    record_list = paginator.get_page(page)

    return render(request,"record/run_record.html", {"context":record_list, "distance_sum":distance_sum, "month": month, "distance_sum_not":distance_sum_not})

def recordUpdateView(request,pk,record_id):
    record = Record.objects.filter(user=pk).get(record_id=record_id)
    return render(request,"record/run_update.html", {"record_id":record_id, "record":record})

def recordUpdate(request,pk,record_id):
    record = Record.objects.filter(user=pk).get(record_id=record_id)
    if request.method == "POST":
        record.title = request.POST["title"]
        record.user = request.user
        record.record_date = request.POST["record_date"]
        if request.FILES.get("image") is not None:
            record.image = request.FILES["image"]
        record.distance = request.POST["distance"]
        record.pace_m = request.POST["pace_m"]
        record.pace_s = request.POST["pace_s"]
        if request.POST["time_h"] == '':
            record.time_h = None
        else:
            record.time_h = request.POST["time_h"]
        record.time_m = request.POST["time_m"]
        record.time_s = request.POST["time_s"]
        record.desc = request.POST["desc"]
        record.save()
        return redirect("runres:recordview",pk=pk)
    else:
        return redirect("runres:recordview",pk=pk)
    

def recordRank(request):
    month = request.GET.get('month')
    team = request.GET.get('team')
    team_list = Team.objects.all()

    if (month =="0" or month == None) and (team == None or team =="0"):
        record = Record.objects.values('user__username','user__first_name','user__last_name').annotate(record_sum=Sum('distance')).order_by('-record_sum')
        distance_sum = Record.objects.filter(confirmed=True).aggregate(Sum('distance'))
    elif (month =="0" or month == None) and team != None:
        record = Record.objects.values('user__username','user__first_name','user__last_name').annotate(record_sum=Sum('distance')).order_by('-record_sum').filter(user__teammember__team=team)
        distance_sum = record.filter(confirmed=True).aggregate(Sum('distance'))
        team = Team.objects.get(team_id = team)
    else:
        record = Record.objects.filter(record_date__month=month).values('user__username','user__first_name','user__last_name').annotate(record_sum=Sum('distance')).order_by('-record_sum')
        distance_sum = Record.objects.filter(confirmed=True).filter(record_date__month=month).aggregate(Sum('distance'))
    return render(request, "record/record_rank.html", {"record_rank":record, "month":month, "distance_sum":distance_sum, "team":team, "team_list":team_list})

def recordCheck(request):
    record = Record.objects.order_by('-record_date')
    return render(request,"admin/record_check.html", {"record":record})

def recordConfirm(request,id):
    if request.method == "POST":
        record = Record.objects.get(record_id=id)
        record.confirmed = True
        record.save()
    return redirect("runres:recordCheck")

def recordReject(request,id):
    if request.method == "POST":
        record = Record.objects.get(record_id=id)
        record.confirmed = False
        record.save()
    return redirect("runres:recordCheck")

def recordDelete(request,id):
    if request.method == "POST":
        record = Record.objects.get(record_id=id)
        record.confirmed = False
        record.delete()
    return redirect("runres:recordCheck")

def pbRank(request):
    try:
        ranking_tenk = PersonalRecord.objects.filter(category='10K').order_by('record')
        ranking_hm = PersonalRecord.objects.filter(category='HM').order_by('record')
        ranking_fm = PersonalRecord.objects.filter(category='FM').order_by('record')
        print(ranking_fm)
    except:
        ranking_tenk = None 
        ranking_hm = None
        ranking_fm = None   
    return render(request,"pb/run_pb.html", {"ranking_tenk":ranking_tenk, "ranking_hm":ranking_hm, "ranking_fm":ranking_fm})

@login_required
def pbView(request,pk):
    pb_tenk = PersonalRecord.objects.filter(runner=pk).filter(category='10K').first()
    pb_hm = PersonalRecord.objects.filter(runner=pk).filter(category='HM').first()
    pb_fm = PersonalRecord.objects.filter(runner=pk).filter(category='FM').first()

    return render(request,"pb/run_mypb.html", {"pb_tenk":pb_tenk, "pb_hm":pb_hm, "pb_fm":pb_fm})

@login_required
def pbresPage(request,pk,category):
    return render(request,"pb/run_pb_res.html",{"category":category})

@login_required
def pbRes(request, pk, category):
    if request.method == "POST":
        mypb = PersonalRecord()
        if request.POST["time_h"] == "":
            h = 0
        else:
            h = int(request.POST["time_h"])
        m = int(request.POST["time_m"])
        s = int(request.POST["time_s"])
        mypb.event_name = request.POST["title"]
        mypb.runner = request.user
        mypb.date = request.POST["date"]
        mypb.evidence_url = request.FILES["image"]
        mypb.category = category
        mypb.record = timedelta(hours=h, minutes=m, seconds=s)
        mypb.desc = request.POST["desc"]
        mypb.save()
        return redirect("runres:pbView", pk)
    else:
        return redirect("runres:pbView", pk)

@login_required
def pbUpdateView(request,pk,category):
    record = PersonalRecord.objects.filter(runner=pk).filter(category=category).first()
    return render(request,"pb/run_pb_update.html", {"record":record})

@login_required
def pbUpdate(request,pk,category):

    record = PersonalRecord.objects.filter(runner=pk).get(category=category)

    if request.method == "POST":
        if request.POST["time_h"] == "":
            h = 0
        else:
            h = int(request.POST["time_h"])
        m = int(request.POST["time_m"])
        s = int(request.POST["time_s"])
        record.event_name = request.POST["title"]
        record.runner = request.user
        record.date = request.POST["date"]
        record.status = "pending"
        record.evidence_url = request.FILES["image"]
        record.category = category
        record.record = timedelta(hours=h, minutes=m, seconds=s)
        record.desc = request.POST["desc"]
        record.save()
        return redirect("runres:pbView", pk)
    else:
        return redirect("runres:pbView", pk)

def runPbCheck(request):
    record = PersonalRecord.objects.order_by('-created_at')
    return render(request,"admin/run_pb_check.html", {"record":record})

def pbConfirm(request,id):
    if request.method == "POST":
        record = PersonalRecord.objects.get(id=id)
        record.status = 'verified'
        record.save()
    return redirect("runres:runPbCheck")

def pbReject(request,id):
    if request.method == "POST":
        record = PersonalRecord.objects.get(id=id)
        record.status = 'rejected'
        record.save()
    return redirect("runres:runPbCheck")

def pbDelete(request,id):
    if request.method == "POST":
        record = PersonalRecord.objects.get(id=id)
        record.delete()
    return redirect("runres:runPbCheck")

def team_assign_view(request):
    teams = Team.objects.all()
    users = User.objects.all()

    # 현재 팀 배정 정보 맵핑
    tm = TeamMember.objects.select_related('user', 'team')
    current_map = {t.user_id: t.team_id for t in tm}

    # users 에 current_team_id 속성을 임시로 붙이기
    for u in users:
        u.current_team_id = current_map.get(u.id)

    return render(request, "admin/team_assign.html", {
        "teams": teams,
        "members": users,  # 템플릿에서 members 로 사용

templates/record/run_record.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <div class="main-view">
    <div class="space-h30"></div>
    <div>
      <p class="page-title">나의 마일리지</p>
    </div>
    <div class="container-500">
      <div class="run-submit-prev">
        <div class="previous-btn">
          <a href="{{ request.META.HTTP_REFERER }}">
            <img src="{% static "img/circle-arrow-down.png" %}" alt="logo-top" height="50px" ,="," width="auto"></a>
        </div>
      </div>
    </div>
    <div class="width500">
      <div class="space-h30"></div>
    </div>
    <div class="search-sum">
      <div class="filter-line">
        <div class="filter-card flex-row">
          <form action="{% url 'runres:recordview' user.pk %}" method="get" id="month-filter">
            <select name="month" class="month-filter">
              <option value="0">all</option>
              <option value="1">1</option>
              <option value="2">2</option>
              <option value="3">3</option>
              <option value="4">4</option>
              <option value="5">5</option>
              <option value="6">6</option>
              <option value="7">7</option>
              <option value="8">8</option>
              <option value="9">9</option>
              <option value="10">10</option>
              <option value="11">11</option>
              <option value="12">12</option>
            </select>
          </form>
        </div>
        <div class="month-filter-txt">월</div>
      </div>
      <div class="distance-sum">합계
        {{ distance_sum.distance__sum | floatformat:2 }}
        |
        {{ distance_sum_not.distance__sum | floatformat:2 }}
        km</div>
    </div>
    <div class="record-wrap-container">
      {% for data in context %}
        <div class="record-list-container">
          <a href="{% url 'runres:recordUpdateView' user.pk data.record_id %}">
            <div class="main-info-1 fade-in-up-short">
              <div class="record-img">
                {% if data.confirmed %}
                  <div class="cf-check">
                    <img src="{% static "img/check_circle_icon.png" %}" alt="logo" height="20px" width="auto">
                  </div>
                {% endif %}
                <img src="/media/{{ data.image }}" alt="logo-top" height="100px" width="100px">
              </div>

              <div class="title-date">
                <div class="record-date">{{ data.record_date | date:"Y-m-d" }}</div>
                <div class="record-title">{{ data.title }}</div>
                <div class="record-3">
                  <div class="record-part-box">
                    <div class="distance-txt">거리</div>
                    <div class="record-distance">{{ data.distance }}
                      km</div>
                  </div>
                  <div class="record-part-box">
                    <div class="distance-txt">페이스</div>
                    {% if data.pace_s < 10 %}
                      <div class="record-pace">{{ data.pace_m }}' 0{{ data.pace_s }}''</div>
                    {% else %}
                      <div class="record-pace">{{ data.pace_m }}'
                        {{ data.pace_s }}''</div>
                    {% endif %}
                  </div>
                  <div class="record-part-box">
                    <div class="distance-txt">기록</div>
                    {% if data.time_s < 10 %}
                      {% if data.time_h is not None %}
                        <div class="record-time">
                          {{ data.time_h }}:{{ data.time_m }}:0{{ data.time_s }}</div>
                      {% else %}
                        <div class="record-time">
                          {{ data.time_m }}:0{{ data.time_s }}</div>
                      {% endif %}
                    {% else %}
                      {% if data.time_h is not None %}
                        <div class="record-time">
                          {{ data.time_h }}:{{ data.time_m }}:{{ data.time_s }}</div>
                      {% else %}
                        <div class="record-time">
                          {{ data.time_m }}:{{ data.time_s }}</div>
                      {% endif %}
                    {% endif %}
                  </div>
                </div>

              </div>

            </div>
          </a>
          {% if data.team != None %}
            <div class="distance-txt">* 팀 :
              {{ data.team }}</div>
          {% endif %}
          <div class="record-desc fade-in-up-short2">{{ data.desc }}</div>
        </div>

      {% endfor %}
    </div>
    <div class="pagenation-container">
      {% if context.has_previous %}
        <a class="page-link" href="?month={{ month }}&p={{ context.previous_page_number }}">
          <div class="page-item">< </div>
        </a>
      {% else %}
        <a class="page-link" href="#">
          <div class="page-item disabled">< </div>
        </a>
      {% endif %}
      <div class="page-num">
        {{ context.number }}/{{ context.paginator.num_pages }}
      </div>
      {% if context.has_next %}
        <a class="page-link" href="?month={{ month }}&p={{ context.next_page_number }}">
          <div class="page-item">></div>
        </a>
      {% else %}
        <a class="page-link" href="#">
          <div class="page-item disabled">></div>
        </a>
      {% endif %}

    </div>
    <div class="space-h30"></div>
    <div class="btn-container">
      <a href="{% url 'runres:runres' %}">
        <div class="upload-btn">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" height="24" viewbox="0 0 24 24" width="24">
            <g stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
              <path d="m4.75 14.75v1.5c0 1.6569 1.34315 3 3 3h8.5c1.6569 0 3-1.3431 3-3v-1.5"/>
              <path d="m12 14.25v-9.25"/>
              <path d="m8.75 8.25 3.25-3.5 3.25 3.5"/>
            </g>
          </svg>
          <div class="upload-txt">마일리지 업로드</div>
        </div>
      </a>
    </div>
  </div>
  <script>
    // 페이지가 모두 로드되면 호출
    window.addEventListener('load', function () {
      const loader = document.getElementById('loader');
      const content = document.getElementById('content');
      // 로딩 화면 숨기기
      loader.style.display = 'none';
      // 콘텐츠 보여주기
      content.style.display = 'block';
    });
  </script>
{% endblock content %}

templates/record/run_res.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">

  <head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
    <meta name="description" content="sterun"/>
    <meta name="keywords" content="sterun"/>
    <title>STERUN</title>
    <link rel="shortcut icon" href="#"/>
    <!-- FONT -->
    <style>
      @import url("https://fonts.googleapis.com/css2?family=Rubik+Glitch&display=swap");
      @import url("https://fonts.googleapis.com/css2?family=Tektur:wght@500;600&display=swap");
      @import url("https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@200;400;600&display=swap");
    </style>
    <link href="https://hangeul.pstatic.net/hangeul_static/css/nanum-square-neo.css" rel="stylesheet">
    <!-- CSS only -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/joolmag.css' %}"/>
    <!--google icon-->
    <script src="https://kit.fontawesome.com/2f3227cf14.js" crossorigin="anonymous"></script>
    <!--js-->
    <script defer="defer" src="{% static 'js/main.js' %}"></script>
  </head>

  {% if user.is_authenticated %}

    <body class="mainbg">
      <div class="sterun-logo-m">
        <a href={% url "index" %}>
          <img src="{% static "img/index_logo.png" %}" alt="logo-top" height="auto" ,="," width="200px">
        </a>
      </div>
      <div class="run-submit-title">
        <div class="sub-title">기록 업로드하기</div>
      </div>
      <div class="container-400">
        <div class="run-submit-prev">
          <div class="previous-btn">
            <a href="{{ request.META.HTTP_REFERER }}">
              <img src="{% static "img/circle-arrow-down.png" %}" alt="logo-top" height="50px" ,="," width="auto"></a>
          </div>
        </div>
      </div>
      <div class="run-form-container">
        <form method="post" id="contactForm" class="run-sm-form" name="contactForm" action="{% url 'runres:recordres' %}" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-control">
            <div class="form-label">달리기 이름
            </div><input class="run-input" id="title" name="title" placeholder="달리기 이름을 입력해 주세요" type="text" required=""/>
          </div>
          <div class="form-control">
            <div class="form-label">팀 선택</div>
            <div class="form-label-80">
              {% for team in my_team %}
                참고로, 지금 나의 팀은
                {{ team.team }}
              {% endfor %}
            </div>
            <select class="run-input" id="team" name="team">
              <option value="" selected="selected">-</option>
              {% for team in team_list %}
                <option value="{{ team.team_id }}">{{ team.team_name }}</option>
              {% endfor %}
            </select>
          </div>
          <div class="form-control">
            <div class="form-label">날짜
            </div><input class="run-input" type="date" name="record_date" required="" id="record_date">
          </div>
          <div class="form-control">
            <div class="form-label">기록 화면
            </div><input class="run-input" type="file" name="image" required="" id="image">
          </div>
          <div class="form-control">
            <div class="form-label">거리 (Km)
            </div><input class="run-input" type="text" name="distance" placeholder="달린 거리를 km 단위로 입력해 주세요" id="distance">
          </div>
          <div class="form-control">
            <div class="form-label">시간
            </div>
            <div class="ms-row">
              <input class="run-input-t" type="number" name="time_h" id="time_h">
              <div class="ms-txt">시간</div>
              <input class="run-input-t" type="number" name="time_m" required="" id="time_m">
              <div class="ms-txt">분</div>
              <input class="run-input-t" type="number" name="time_s" required="" id="time_s">
              <div class="ms-txt">초</div>
            </div>
          </div>
          <div class="form-control">
            <div class="form-label">페이스 (자동입력)
            </div>
            <div class="ms-row">
              <input class="run-input-t" type="number" name="pace_m" required="" id="pace_m" readonly="readonly">
              <div class="ms-txt">분</div>
              <input class="run-input-t" type="number" name="pace_s" required="" id="pace_s" readonly="readonly">
              <div class="ms-txt">초</div>
            </div>
          </div>

          <div class="form-control">
            <div class="form-label">노트
            </div>
            <textarea class="run-input" id="inputMessage" name="desc" placeholder="노트를 남겨 주세요" data-parsley-pattern="^[a-zA-Z0-9\s.:,!?']+$"></textarea>
          </div>
          <div class="btn-control">
            <button type="submit" name="submit" id="submit-form-btn" class="submit-btn">
              <p class="btn-text">등록하기</p>
              <span class="spinner-login"></span>
            </button>
          </div>
        </form>
      </div>
      <div class="space-h30"></div>

      <script>
        const btn = document.getElementById('submit-form-btn');
        const form = document.getElementById('contactForm');
        btn.addEventListener('click', () => {
          if (form.checkValidity()) {
            btn
              .classList
              .add('loading-login'); // 브라우저 기본 alert도 출력
          }
          // 로그인 처리 시뮬레이션 (예: 2초 후 완료)
          setTimeout(() => {
            btn
              .classList
              .remove('loading-login');
          }, 20000);
        });

        function calcValues() {
          // 입력값 3개
          let a = parseFloat(document.getElementById('time_h').value) || 0;
          let b = parseFloat(document.getElementById('time_m').value) || 0;
          let c = parseFloat(document.getElementById('time_s').value) || 0;
          let d = parseFloat(document.getElementById('distance').value) || 0;

          let r1 = (a * 60) + b + (c / 60);
          let r2 = r1 / d;
          let pm = parseInt(r2 / 1);
          let ps = (r2 % 1) * 60;

          console.log(pm);
          console.log(ps);

          document
            .getElementById('pace_m')
            .value = pm;
          document
            .getElementById('pace_s')
            .value = ps.toFixed(0);
        }

        document
          .getElementById('time_h')
          .addEventListener('input', calcValues);
        document
          .getElementById('time_m')
          .addEventListener('input', calcValues);
        document
          .getElementById('time_s')
          .addEventListener('input', calcValues);
        document
          .getElementById('distance')
          .addEventListener('input', calcValues);
      </script>
    </body>
  {% else %}

    <body class="login-page">
      <div class="login-container">
        <div class="login-page-top-margin"></div>
        <div class="j-navbar-brand">
          <a href="{% url 'index' %}">
            <img src="{% static "img/logo2@.png" %}" alt="logo-top" height="auto," width="auto">
          </a>
        </div>
        <div>
          <div class="login-container">
            <form method="post" action="{% url 'users:login' %}" class="form-container">
              {% csrf_token %}
              {% include "users/form_errors.html" %}
              <div>
                <input type="text" name="username" id="username" class="id" placeholder="아이디">
              </div>
              <div>
                <input type="text" name="password" id="password" class="pw" placeholder="비밀번호">
              </div>
              <div>
                <button type="submit" class="login-submit">로그인</button>
              </div>
              <a href="{% url 'users:signup' %}">
                <span class="signup-btn">회원가입</span></a>
            </form>
          </div>
        </div>
      </div>
    </body>
  {% endif %}

</html>