bingo/urls.py
from django.urls import path

from . import views

app_name = "bingo"

urlpatterns = [
    path("<str:pk>", views.bingo, name="bingo"),
    path("createbingo/<str:pk>", views.create_bingo, name="create_bingo"),
    path("update-public-status/<str:pk>", views.update_public_status, name="update_public_status"),
    path("bingoupdate/<str:pk>", views.bingoupdate, name="bingoupdate"),
    path("bingores/<str:pk>", views.bingores, name="bingores"),
    path("bingoreset/", views.bingoreset, name="bingoreset"),
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path('go-back/', views.go_back_view, name='go_back'),
    path('setting/', views.setting_page, name='setting_page'),
]

steruncomm/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path('users/', include('users.urls')),
    path("attendance/", include("attendance.urls")),
    path("runres/", include("record.urls")),
    path("bingo/", include("bingo.urls")),
    path("article/", include("article.urls")),
    path("marathon/", include("marathon.urls")),
    path('summernote/', include('django_summernote.urls')),  # summernote URL 추가
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import *

app_name = "users"
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name = "users/login.html"), name = "login"),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
]

bingo/models.py
from django.conf import settings
from django.db import models
from django_resized import ResizedImageField
from multiselectfield import MultiSelectField

# def image_upload_path(instance, filename):
#    time = timezone.now()
#    return f"{instance}/{time}+{filename}"

class BingoItem(models.Model):
    item_id = models.IntegerField(primary_key=True)
    content = models.CharField(max_length=100, blank=False, null=False)
    row = models.IntegerField(null=False, blank=False)
    col = models.IntegerField(null=False, blank=False)

    def __str__(self):
        return str(self.content) + "_id_" + (str(self.item_id)) + "|" + str(self.row) + "_" + str(self.col) 
    
class BingoCheck(models.Model):
    bingo_item = models.ForeignKey(BingoItem, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return str(self.user) + "_" + str(self.bingo_item) + "_" + str(self.completed)

bingo/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.db.models import Sum
from django.core.paginator import Paginator
from django.http import JsonResponse
import json
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User

from bingo.models import *
from record.models import Record

def bingo(request, pk):
    user = get_object_or_404(User, pk=pk)
    login_user = request.user
    if user == login_user:
        user_matched = 1
    else:
        user_matched = None
    print(user_matched)
    bingo_item_1r = BingoCheck.objects.select_related("bingo_item").filter(user=pk).filter(bingo_item__row=1)
    bingo_item_2r = BingoCheck.objects.select_related("bingo_item").filter(user=pk).filter(bingo_item__row=2)
    bingo_item_3r = BingoCheck.objects.select_related("bingo_item").filter(user=pk).filter(bingo_item__row=3)
    bingo_item_4r = BingoCheck.objects.select_related("bingo_item").filter(user=pk).filter(bingo_item__row=4)
    bingo_item_5r = BingoCheck.objects.select_related("bingo_item").filter(user=pk).filter(bingo_item__row=5)
    lenof5l = len(bingo_item_5r)
    return render(request,"bingo/bingo.html",{"bingo_item_1r":bingo_item_1r, "bingo_item_2r":bingo_item_2r, "bingo_item_3r":bingo_item_3r, "bingo_item_4r":bingo_item_4r, "bingo_item_5r":bingo_item_5r, "user_id":pk, "len":lenof5l,"user":user, "user_matched":user_matched})

def create_bingo(request, pk):
    i = 1
    while i <= 25:
        bingoitem = BingoItem.objects.filter(item_id = i)
        existing = BingoCheck.objects.filter(bingo_item = bingoitem[0]).filter(user=request.user).exists()
        print(bingoitem)
        if not existing:
            bingocheck = BingoCheck(
                bingo_item = bingoitem[0],
                user = request.user,
                completed = False
            )
            bingocheck.save()
            print(request.user)
        i+=1
    return redirect("bingo:bingo", pk)


def update_public_status(request,pk):
    log_user = request.user
    bin_user = get_object_or_404(User, pk=pk)
    if request.method == "POST":
        data = json.loads(request.body)
        print(data)
        bingo_id = data.get("bingo_id")
        is_checked = data.get("is_checked")
        print(is_checked)
        if log_user == bin_user:
            try:
                bingo_item = BingoCheck.objects.filter(user=request.user).get(bingo_item__item_id=bingo_id)
                if is_checked == False:
                    bingo_item.completed = False
                    bingo_item.save()
                else:
                    bingo_item.completed = True
                    bingo_item.save()
                return JsonResponse({"status": "success", "checked": bingo_item.completed})
            except BingoCheck.DoesNotExist:
                return JsonResponse({"status": "error", "message": "Post not found"}, status=404)
        else:
            return JsonResponse({"status": "success", "message": "log_user is not bin_user"})

    return JsonResponse({"error": "Invalid request"}, status=400)

def bingoupdate(request,pk):

    bingoitem = BingoItem.objects.all()
    cnt_items = bingoitem.count()
    
    return render(request, "bingo/bingo_res.html", {"bingoitem":bingoitem, "cnt_items":cnt_items})

def bingores(request, pk):

    if request.method == "POST":
        items = BingoItem.objects.all()

        i=1
        while i < 26:
            BingoItem.objects.filter(item_id=i).update(content=request.POST.get("content"+str(i)))
            i+=1
        return render(request, "index.html")
    else:
        return render(request, "index.html")
    
def bingoreset(request):

    if request.method == "POST":

        items = BingoItem()
        cnt_items = BingoItem.objects.all().conut()

        i=1
        while i < 6:
            k=1
            while k < 6:
                items.content = str(i)+str(k)
                items.row = i
                items.col = k
                items.save()
                k+=1
            i+=1
        return render(request, "index.html")
    
    return render(request, "index.html", {"cnt_items":cnt_items})

templates/bingo/bingo.html
{% extends "base.html" %}
{% load static %}
{% block content %}

  {% csrf_token %}
  <div class="space-h30"></div>
  <div class="flex-container container-400">
    <div class="bingo-title">{{ user.last_name }}{{ user.first_name }}
      님의 빙고</div>
  </div>

  <div class="bingo-board fade-in-up-short">
    <div class="bingo-row">
      {% for item in bingo_item_1r %}
        <label for="{{ item.bingo_item.item_id }}">
          <div class="bingo-col" id="item{{ item.bingo_item.item_id }}">
            <input type="checkbox" name="item" id="{{ item.bingo_item.item_id }}" data-post-id="{{ item.bingo_item.item_id }}" {% if item.completed %} checked="checked" {% endif %}>
            {{ item.bingo_item.content }}
            <div id="bingo-img{{ item.bingo_item.item_id }}" class="bingo-img">
              <img class="bingo-stamp" src="{% static "img/Ellipse-1.svg" %}" alt="main-img" height="auto," width="auto">
            </div>
          </div>
        </label>

      {% endfor %}
    </div>
    <div class="bingo-row">
      {% for item in bingo_item_2r %}
        <label for="{{ item.bingo_item.item_id }}">
          <div class="bingo-col" id="item{{ item.bingo_item.item_id }}">
            <input type="checkbox" name="item" id="{{ item.bingo_item.item_id }}" data-post-id="{{ item.bingo_item.item_id }}" {% if item.completed %} checked="checked" {% endif %}>
            {{ item.bingo_item.content }}
            <div id="bingo-img{{ item.bingo_item.item_id }}" class="bingo-img">
              <img class="bingo-stamp" src="{% static "img/Ellipse-1.svg" %}" alt="main-img" height="auto," width="auto">
            </div>
          </div>
        </label>
      {% endfor %}
    </div>
    <div class="bingo-row">
      {% for item in bingo_item_3r %}
        <label for="{{ item.bingo_item.item_id }}">
          <div class="bingo-col" id="item{{ item.bingo_item.item_id }}">
            <input type="checkbox" name="item" id="{{ item.bingo_item.item_id }}" data-post-id="{{ item.bingo_item.item_id }}" {% if item.completed %} checked="checked" {% endif %}>
            {{ item.bingo_item.content }}
            <div id="bingo-img{{ item.bingo_item.item_id }}" class="bingo-img">
              <img class="bingo-stamp" src="{% static "img/Ellipse-1.svg" %}" alt="main-img" height="auto," width="auto">
            </div>
          </div>
        </label>
      {% endfor %}
    </div>
    <div class="bingo-row">
      {% for item in bingo_item_4r %}
        <label for="{{ item.bingo_item.item_id }}">
          <div class="bingo-col" id="item{{ item.bingo_item.item_id }}">
            <input type="checkbox" name="item" id="{{ item.bingo_item.item_id }}" data-post-id="{{ item.bingo_item.item_id }}" {% if item.completed %} checked="checked" {% endif %}>
            {{ item.bingo_item.content }}
            <div id="bingo-img{{ item.bingo_item.item_id }}" class="bingo-img">
              <img class="bingo-stamp" src="{% static "img/Ellipse-1.svg" %}" alt="main-img" height="auto," width="auto">
            </div>
          </div>
        </label>
      {% endfor %}
    </div>
    <div class="bingo-row">
      {% for item in bingo_item_5r %}
        <label for="{{ item.bingo_item.item_id }}">
          <div class="bingo-col" id="item{{ item.bingo_item.item_id }}">
            <input type="checkbox" name="item" id="{{ item.bingo_item.item_id }}" data-post-id="{{ item.bingo_item.item_id }}" {% if item.completed %} checked="checked" {% endif %}>
            {{ item.bingo_item.content }}
            <div id="bingo-img{{ item.bingo_item.item_id }}" class="bingo-img">
              <img class="bingo-stamp" src="{% static "img/Ellipse-1.svg" %}" alt="main-img" height="auto" width="auto">
            </div>
          </div>
        </label>
      {% endfor %}
    </div>
  </div>
  {% if len != 5 %}
    <a href="{% url 'bingo:create_bingo' user.pk %}">
      <div class="create-bingo-btn">빙고 만들기</div>
    </a>
  {% endif %}
  {% if user_matched == 1 %}
    <div class="go-center">
      <button id="kakao-share-btn" class="kakao-btn">
        <img src="{% static "img/KakaoTalk_logo.png" %}" alt="" height="30px" width="30px">
        <div>카카오톡 공유</div>
      </button>
    </div>
  {% else %}
    <div class="hidden">
      <button id="kakao-share-btn">
        <div>카카오톡 공유</div>
      </button>
    </div>
  {% endif %}
  <!-- 모달 오버레이 -->
  <div id="NoModal" class="modal-overlay">
    <div class="modal-box">
      <div class="flex-row-bt">
        <h3>취소하기</h3>
        <button type="button" class="delmodal-btn" id="closeNoModal">X</button>
      </div>
      <p>정말 취소하시겠습니까?</p>
      <div class="modal-buttons">
        <button type="button" class="bingocheck-btn" id="bingo-no">취소</button>
      </div>
    </div>
  </div>
  <div id="YesModal" class="modal-overlay">
    <div class="modal-box">
      <div class="flex-row-bt">
        <h3>완료하기</h3>
        <button type="button" class="delmodal-btn" id="closeYesModal">X</button>
      </div>
      <p>정말 완료하시겠습니까?</p>
      <div class="modal-buttons">
        <button type="button" class="bingocheck-btn" id="bingo-yes">완료</button>
      </div>
    </div>
  </div>
  {% csrf_token %}
  <input type="hidden" id="csrf-token" value="{{ csrf_token }}">

  <script>
    document
      .getElementById('kakao-share-btn')
      .addEventListener('click', function () {
        Kakao
          .Share
          .sendDefault({
            objectType: 'feed',
            content: {
              title: "Running-Bingo",
              description: "{{ user.username }}님의 빙고를 확인해 보세요:)",
              imageUrl: "https://joollab.com/static/img/logo2%40.png",
              link: {
                mobileWebUrl: "https://joollab.com/bingo/" + "{{ user.pk }}",
                webUrl: "https://joollab.com/bingo/" + "{{ user.pk }}"
              }
            },
            buttons: [
              {
                title: '보러가기',
                link: {
                  mobileWebUrl: "https://joollab.com/bingo/" + "{{ user.pk }}",
                  webUrl: "https://joollab.com/bingo/" + "{{ user.pk }}"
                }
              }
            ]
          });
      });
  </script>
  <script>
    const nomodal = document.getElementById("NoModal");
    const yesmodal = document.getElementById("YesModal");

    function closeYesModal() {
      yesmodal
        .classList
        .remove("active");
    }

    function closeNoModal() {
      nomodal
        .classList
        .remove("active");
    }

    const csrfToken = document
      .getElementById('csrf-token')
      .value;
    const user_matched = "{{ user_matched }}";
    const user_id = "{{ user_id }}";

    // 현재 어떤 체크박스를 처리 중인지 저장할 변수들
    let currentCheckbox = null;
    let currentBingoImg = null;
    let currentBingoId = null;

    // ✅ 공통으로 서버 업데이트하는 함수
    function updateBingoStatus(isChecked) {
      if (!currentBingoId) 
        return;
      
      return fetch("/bingo/update-public-status/" + user_id, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "X-CSRFToken": csrfToken
        },
        body: JSON.stringify({bingo_id: currentBingoId, is_checked: isChecked})
      })
        .then(response => response.json())
        .then(data => {
          console.log("업데이트 결과:", data);
        })
        .catch(err => console.error("에러:", err));
    }

    // ✅ 체크박스 루프
    for (let i = 1; i < 26; i++) {
      const checkbox = document.getElementById(i);
      const bingo_img = document.getElementById('bingo-img' + i);

      if (!checkbox || !bingo_img) 
        continue;
      
      // 초기 상태에 따라 이미지 표시
      bingo_img.style.display = checkbox.checked
        ? 'block'
        : 'none';

      checkbox.addEventListener('change', function () {
        if (user_matched != 1) {
          // user_matched 가 1이 아닌 경우 아무 것도 하지 않음
          return;
        }

        // 현재 클릭된 정보 저장
        currentCheckbox = this;
        currentBingoImg = bingo_img;
        currentBingoId = this.dataset.postId;

        if (this.checked === false) {
          // ✅ 체크 해제 → NoModal 오픈
          nomodal
            .classList
            .add("active");
        } else {
          // ✅ 체크 → YesModal 오픈
          yesmodal
            .classList
            .add("active");
        }
      });
    }

    /* ==========================
       ❌ NoModal 이벤트 (한 번만 등록)
       ========================== */

    // "예, 비공개로 돌릴게요" 같은 버튼
    document
      .getElementById("bingo-no")
      .addEventListener("click", function (e) {
        if (!currentCheckbox || !currentBingoImg) 
          return;
        
        updateBingoStatus(false).then(() => {
          currentCheckbox.checked = false;
          currentBingoImg.style.display = 'none';
          closeNoModal();
        });
      });

    // 모달 바깥 눌렀을 때 닫기 + 원상복구(취소)
    nomodal.addEventListener("click", function (e) {
      if (e.target === this) {
        closeNoModal();
        if (currentCheckbox) {
          currentCheckbox.checked = true; // 해제 시도 취소 → 다시 체크
          if (currentBingoImg) 
            currentBingoImg.style.display = 'block';
          }
        }
    });

    // X 버튼 눌렀을 때 닫기 + 원상복구(취소)
    document
      .getElementById("closeNoModal")
      .addEventListener("click", function (e) {
        closeNoModal();
        if (currentCheckbox) {
          currentCheckbox.checked = true;
          if (currentBingoImg) 
            currentBingoImg.style.display = 'block';
          }
        });

    /* ==========================
       ✅ YesModal 이벤트 (한 번만 등록)
       ========================== */

    // "예, 공개로 할게요" 같은 버튼
    document
      .getElementById("bingo-yes")
      .addEventListener("click", function (e) {
        if (!currentCheckbox || !currentBingoImg) 
          return;
        
        updateBingoStatus(true).then(() => {
          currentCheckbox.checked = true;
          currentBingoImg.style.display = 'block';
          closeYesModal();
        });
      });

    // 모달 바깥 눌렀을 때 닫기 + 원상복구(취소)
    yesmodal.addEventListener("click", function (e) {
      if (e.target === this) {
        closeYesModal();
        if (currentCheckbox) {
          currentCheckbox.checked = false; // 체크 시도 취소 → 다시 해제
          if (currentBingoImg) 
            currentBingoImg.style.display = 'none';
          }
        }
    });

    // X 버튼 눌렀을 때 닫기 + 원상복구(취소)
    document
      .getElementById("closeYesModal")
      .addEventListener("click", function (e) {
        closeYesModal();
        if (currentCheckbox) {
          currentCheckbox.checked = false;
          if (currentBingoImg) 
            currentBingoImg.style.display = 'none';
          }
        });
  </script>

{% endblock content %}

templates/bingo/bingo_res.html
{% extends "base.html" %}
{% load static %}
{% block content %}

  {% if user.is_authenticated %}

    <body class="mainbg">
      <div class="run-submit-title">
        빙고 아이템 변경
      </div>
      <div class="flex-center">
        <div class="container-w500">
          <div class="run-submit-prev">
            <div class="previous-btn">
              <a href="{{ request.META.HTTP_REFERER }}">
                <img src="{% static "img/circle-arrow-down.png" %}" alt="logo-top" height="50px" ,="," width="auto"></a>
            </div>
          </div>
        </div>
      </div>
      <div class="run-form-container">
        <form method="post" id="contactForm" class="run-sm-form" name="contactForm" action="{% url 'bingo:bingores' user.pk %}" enctype="multipart/form-data">
          {% csrf_token %}

          {% for item in bingoitem %}
            <div class="form-control">
              <div class="form-label">아이템{{ item.item_id }}
              </div><input class="run-input" id="content{{ item.item_id }}" name="content{{ item.item_id }}" value="{{ item.content }}" type="text" required=""/>
            </div>
          {% endfor %}

          <div class="btn-control">
            <button type="submit" name="submit" id="submit-form-btn" class="submit-btn">
              수정하기
            </button>
          </div>
        </form>
      </div>

    </body>
  {% else %}

    <body class="login-page">
      <div class="login-container">
        <div class="login-page-top-margin"></div>
        <div class="j-navbar-brand">
          <a href="{% url 'index' %}">
            <img src="{% static "img/logo2@.png" %}" alt="logo-top" height="auto," width="auto">
          </a>
        </div>
        <div>
          <div class="login-container">
            <form method="post" action="{% url 'users:login' %}" class="form-container">
              {% csrf_token %}
              {% include "users/form_errors.html" %}
              <div>
                <input type="text" name="username" id="username" class="id" placeholder="아이디">
              </div>
              <div>
                <input type="text" name="password" id="password" class="pw" placeholder="비밀번호">
              </div>
              <div>
                <button type="submit" class="login-submit">로그인</button>
              </div>
              <a href="{% url 'users:signup' %}">
                <span class="signup-btn">회원가입</span></a>
            </form>
          </div>
        </div>
      </div>
    </body>
  {% endif %}

{% endblock content %}