main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path('go-back/', views.go_back_view, name='go_back'),
    path('setting/', views.setting_page, name='setting_page'),
]

record/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = "runres"

urlpatterns = [
    path("resister/", views.runres, name="runres"),
    path('recordres/', views.recordres, name='recordres'),
    path('recordview/<str:pk>/', views.recordview, name='recordview'),
    path('recordUpdateView/<str:pk>/<str:record_id>', views.recordUpdateView, name='recordUpdateView'),
    path('recordUpdate/<str:pk>/<str:record_id>', views.recordUpdate, name='recordUpdate'),
    path('recordrank/', views.recordRank, name="recordRank"),
    path('recordCheck/', views.recordCheck, name="recordCheck"),
    path('recordConfirm/<str:id>', views.recordConfirm, name="recordConfirm"),
    path('recordReject/<str:id>', views.recordReject, name="recordReject"),
    path('recordDelete/<str:id>', views.recordDelete, name="recordDelete"),
    path('pbrank/', views.pbRank, name="pbRank"),
    path('pbview/<str:pk>/', views.pbView, name="pbView"),
    path('pbresPage/<str:pk>/<str:category>/', views.pbresPage, name="pbresPage"),
    path('pbRes/<str:pk>/<str:category>/', views.pbRes, name="pbRes"),
    path('pbUpdateView/<str:pk>/<str:category>/', views.pbUpdateView, name="pbUpdateView"),
    path('pbUpdate/<str:pk>/<str:category>/', views.pbUpdate, name="pbUpdate"),
    path('runPbCheck/', views.runPbCheck, name="runPbCheck"),
    path('pbConfirm/<str:id>', views.pbConfirm, name="pbConfirm"),
    path('pbReject/<str:id>', views.pbReject, name="pbReject"),
    path('pbDelete/<str:id>', views.pbDelete, name="pbDelete"),
    path('teamassign/', views.team_assign_view, name="team_assign_view"),
    path("teams/assign/save/", views.save_team_members, name="save_team_members"),
]

steruncomm/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path('users/', include('users.urls')),
    path("attendance/", include("attendance.urls")),
    path("runres/", include("record.urls")),
    path("bingo/", include("bingo.urls")),
    path("article/", include("article.urls")),
    path("marathon/", include("marathon.urls")),
    path('summernote/', include('django_summernote.urls')),  # summernote URL 추가
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import *

app_name = "users"
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name = "users/login.html"), name = "login"),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
]

record/models.py
from django.conf import settings
from django.db import models
from django_resized import ResizedImageField
from multiselectfield import MultiSelectField
from django.db.models import UniqueConstraint

# def image_upload_path(instance, filename):
#    time = timezone.now()
#    return f"{instance}/{time}+{filename}"

class Team(models.Model):
    STATUS_CHOICES = [
        ('ready', '준비중'),
        ('go', '운영중'),
        ('stop', '완료'),
    ]
    team_id = models.AutoField(primary_key=True)
    team_name = models.CharField(max_length=50, null=False, blank=False)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default='ready')
    def __str__(self):
        return str(self.team_name)
    
class TeamMember(models.Model):
    member_id = models.AutoField(primary_key=True)
    team = models.ForeignKey(Team, null=True, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    leader = models.BooleanField(default=False)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user'], name='uunique_user_only_one_team')
        ]

    def __str__(self):
        return str(self.team)+"_"+str(self.user)

class Record(models.Model):
    record_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    team = models.ForeignKey(Team, null=True, blank=True, on_delete=models.SET_NULL)
    record_date = models.DateField(blank=True, null=True)
    image = ResizedImageField(size=[500,500], upload_to="record", blank=False)
    distance = models.DecimalField(max_digits=6, decimal_places=2, blank=False, null=False)
    pace_m = models.IntegerField(null=True, blank=True)
    pace_s = models.IntegerField(null=True, blank=True)
    time_h = models.IntegerField(null=True, blank=True)
    time_m = models.IntegerField(null=True, blank=True)
    time_s = models.IntegerField(null=True, blank=True)
    desc = models.TextField(blank=True)
    confirmed = models.BooleanField(default=False)

    def delete(self, *args, **kwargs):
        # 실제 파일 삭제
        if self.image:
            self.image.delete(save=False)
        # DB 데이터 삭제
        super().delete(*args, **kwargs)

    def __str__(self):
        return str(self.team)+ "_" + str(self.confirmed)+ "_" + str(self.user) + "_" + str(self.record_date) + "_" + (str(self.title))


class PersonalRecord(models.Model):
    STATUS_CHOICES = [
        ('pending', '심사중'),
        ('verified', '인증됨'),
        ('rejected', '반려됨'),
    ]
    CATEGORY_CHOICES = [
        ('10K', '10km'),
        ('HM', '하프마라톤'),
        ('FM', '풀마라톤'),
    ]
    event_name = models.CharField(max_length=50)
    runner = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    category = models.CharField(max_length=5, choices=CATEGORY_CHOICES)
    date = models.DateField(blank=True, null=True)
    record = models.DurationField()  # 시간 기록
    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default='pending'
    )
    evidence_url = ResizedImageField(size=[500,500], upload_to="record", blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    desc = models.TextField(blank=True)

    def delete(self, *args, **kwargs):
        # 실제 파일 삭제
        if self.evidence_url:
            self.evidence_url.delete(save=False)
        # DB 데이터 삭제
        super().delete(*args, **kwargs)

    class Meta:
        constraints = [
            UniqueConstraint(fields=['runner', 'category'], name='unique_user_category')
        ]

    def __str__(self):
        return f"{self.runner} - {self.category}: {self.record}"

templates/pb/run_mypb.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <div class="main-view flex-center">
    <div class="record-top-space"></div>
    <div class="container-w500">
      <div class="space-h30"></div>
      <div>
        <p class="page-title">나의 PB</p>
      </div>
      <div class="run-submit-prev">
        <div class="previous-btn">
          <a href="{{ request.META.HTTP_REFERER }}">
            <img src="{% static "img/circle-arrow-down.png" %}" alt="logo-top" height="50px" ,="," width="auto"></a>
        </div>
      </div>
      <div class="space-h30"></div>
      <div class="pb-container">
        {% if pb_fm == None %}
          <div class="title-pb">Full PB</div>
          <div class="no-record">기록이 없어요. 등록해 주세요.</div>
          <div class="btn-control">
            <a href="{% url "runres:pbresPage" user.pk "FM" %}">
              <button class="btn-kor">PB등록하기</button>
            </a>
          </div>
        {% else %}
          <div class="flex-row">
            <div class="title-pb">Full PB</div>
            <div class="{% if pb_fm.status == 'verified' %}pb-status-verified
            {% elif pb_fm.status == 'pending' %}pb-status-pending
            {% else %}pb-status-rejected{% endif %}">{{ pb_fm.get_status_display }}</div>
          </div>
          <div class="pb-event">
            <div>
              <i class="fa-solid fa-trophy"></i>
              대회명 :
              {{ pb_fm.event_name }}
            </div>
            <div>
              <i class="fa-regular fa-clock"></i>
              기록 :
              {{ pb_fm.record }}
            </div>
          </div>
          <div class="flex-center">
            <img class="card-main-img" src="/media/{{ pb_fm.evidence_url }}" alt="" height="auto" width="auto"/>
          </div>
          <div class="btn-control">
            <a href="{% url "runres:pbUpdateView" user.pk "FM" %}">
              <button class="btn-kor">PB 갱신하기</button>
            </a>
          </div>
        {% endif %}
      </div>
      <div class="space-h30"></div>
      <div class="pb-container">
        {% if pb_hm == None %}
          <div class="title-pb">Hlaf PB</div>
          <div class="no-record">기록이 없어요. 등록해 주세요.</div>
          <div class="btn-control">
            <a href="{% url "runres:pbresPage" user.pk "HM" %}">
              <button class="btn-kor">PB등록하기</button>
            </a>
          </div>
        {% else %}
          <div class="flex-row">
            <div class="title-pb">Hlaf PB</div>
            <div class="{% if pb_hm.status == 'verified' %}pb-status-verified
            {% elif pb_hm.status == 'pending' %}pb-status-pending
            {% else %}pb-status-rejected{% endif %}">{{ pb_hm.get_status_display }}</div>
          </div>
          <div class="pb-event">
            <div>
              <i class="fa-solid fa-trophy"></i>
              대회명 :
              {{ pb_hm.event_name }}
            </div>
            <div>
              <i class="fa-regular fa-clock"></i>
              기록 :
              {{ pb_hm.record }}
            </div>
          </div>
          <div class="flex-center">
            <img class="card-main-img" src="/media/{{ pb_hm.evidence_url }}" alt="" height="auto" width="auto"/>
          </div>
          <div class="btn-control">
            <a href="{% url "runres:pbUpdateView" user.pk "HM" %}">
              <button class="btn-kor">PB 갱신하기</button>
            </a>
          </div>
        {% endif %}
      </div>
      <div class="space-h30"></div>
      <div class="pb-container">
        {% if pb_tenk == None %}
          <div class="title-pb">10Km PB</div>
          <div class="no-record">기록이 없어요. 등록해 주세요.</div>
          <div class="btn-control">
            <a href="{% url "runres:pbresPage" user.pk "10K" %}">
              <button class="btn-kor">PB등록하기</button>
            </a>
          </div>
        {% else %}
          <div class="flex-row">
            <div class="title-pb">10Km PB</div>
            <div class="{% if pb_tenk.status == 'verified' %}pb-status-verified
            {% elif pb_tenk.status == 'pending' %}pb-status-pending
            {% else %}pb-status-rejected{% endif %}">{{ pb_tenk.get_status_display }}</div>
          </div>
          <div class="pb-event">
            <div>
              <i class="fa-solid fa-trophy"></i>
              대회명 :
              {{ pb_tenk.event_name }}
            </div>
            <div>
              <i class="fa-regular fa-clock"></i>
              기록 :
              {{ pb_tenk.record }}
            </div>
          </div>
          <div class="flex-center">
            <img class="card-main-img" src="/media/{{ pb_tenk.evidence_url }}" alt="" height="auto" width="auto"/>
          </div>
          <div class="btn-control">
            <a href="{% url "runres:pbUpdateView" user.pk "10K" %}">
              <button class="btn-kor">PB 갱신하기</button>
            </a>
          </div>
        {% endif %}
      </div>
    </div>
  </div>
  <script>
    // 페이지가 모두 로드되면 호출
    window.addEventListener('load', function () {
      const loader = document.getElementById('loader');
      const content = document.getElementById('content');
      // 로딩 화면 숨기기
      loader.style.display = 'none';
      // 콘텐츠 보여주기
      content.style.display = 'block';
    });
  </script>
{% endblock content %}

templates/pb/run_pb.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <div class="main-view flex-center">
    <div class="container-w500">
      <div>
        <p class="page-title">PB 랭킹</p>
      </div>
      <div class="pb-container">
        <div class="title-pb">Full PB 순위</div>
        {% for record in ranking_fm %}
          <div class="flex-row text-white">
            {% if forloop.counter == 1 %}
              <div class="rank-counter"><img src="{% static 'img/01-Gold-Medal.png' %}" alt="hamb-btn" height="40px," width="40px"></div>
            {% elif forloop.counter == 2 %}
              <div class="rank-counter"><img src="{% static 'img/02-Silver-Medal.png' %}" alt="hamb-btn" height="40px," width="40px"></div>
            {% elif forloop.counter == 3 %}
              <div class="rank-counter"><img src="{% static 'img/03-Bronze-Medal.png' %}" alt="hamb-btn" height="40px," width="40px"></div>
            {% else %}
              <div class="rank-counter">{{ forloop.counter }}</div>
            {% endif %}
            <div class="rank-runner">{{ record.runner.last_name }}{{ record.runner.first_name }}</div>
            <div class="rank-record">{{ record.record }}</div>
          </div>
        {% endfor %}
      </div>
      <div class="space-h30"></div>
      <div class="pb-container">
        <div class="title-pb">Half PB 순위</div>
        {% for record in ranking_hm %}
          <div class="flex-row text-white">
            {% if forloop.counter == 1 %}
              <div class="rank-counter"><img src="{% static 'img/01-Gold-Medal.png' %}" alt="hamb-btn" height="40px," width="40px"></div>
            {% elif forloop.counter == 2 %}
              <div class="rank-counter"><img src="{% static 'img/02-Silver-Medal.png' %}" alt="hamb-btn" height="40px," width="40px"></div>
            {% elif forloop.counter == 3 %}
              <div class="rank-counter"><img src="{% static 'img/03-Bronze-Medal.png' %}" alt="hamb-btn" height="40px," width="40px"></div>
            {% else %}
              <div class="rank-counter">{{ forloop.counter }}</div>
            {% endif %}
            <div class="rank-runner">{{ record.runner.last_name }}{{ record.runner.first_name }}</div>
            <div class="rank-record">{{ record.record }}</div>
          </div>
        {% endfor %}
      </div>
      <div class="space-h30"></div>
      <div class="pb-container">
        <div class="title-pb">10Km PB 순위</div>
        {% for record in ranking_tenk %}
          <div class="flex-row text-white">
            {% if forloop.counter == 1 %}
              <div class="rank-counter"><img src="{% static 'img/01-Gold-Medal.png' %}" alt="hamb-btn" height="40px," width="40px"></div>
            {% elif forloop.counter == 2 %}
              <div class="rank-counter"><img src="{% static 'img/02-Silver-Medal.png' %}" alt="hamb-btn" height="40px," width="40px"></div>
            {% elif forloop.counter == 3 %}
              <div class="rank-counter"><img src="{% static 'img/03-Bronze-Medal.png' %}" alt="hamb-btn" height="40px," width="40px"></div>
            {% else %}
              <div class="rank-counter">{{ forloop.counter }}</div>
            {% endif %}
            <div class="rank-runner">{{ record.runner.last_name }}{{ record.runner.first_name }}</div>
            <div class="rank-record">{{ record.record }}</div>
          </div>
        {% endfor %}
      </div>
      <div class="space-h30"></div>
      <div class="btn-control">
        <a href="{% url 'runres:pbView' user.pk %}">
          <button class="submit-btn">나의 PB</button>
        </a>
      </div>
    </div>
  </div>
  <script>
    // 페이지가 모두 로드되면 호출
    window.addEventListener('load', function () {
      const loader = document.getElementById('loader');
      const content = document.getElementById('content');
      // 로딩 화면 숨기기
      loader.style.display = 'none';
      // 콘텐츠 보여주기
      content.style.display = 'block';
    });
  </script>
{% endblock content %}

templates/pb/run_pb_res.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">

  <head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
    <meta name="description" content="sterun"/>
    <meta name="keywords" content="sterun"/>
    <title>STERUN</title>
    <link rel="shortcut icon" href="#"/>
    <!-- FONT -->
    <style>
      @import url("https://fonts.googleapis.com/css2?family=Rubik+Glitch&display=swap");
      @import url("https://fonts.googleapis.com/css2?family=Tektur:wght@500;600&display=swap");
      @import url("https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@200;400;600&display=swap");
    </style>
    <link href="https://hangeul.pstatic.net/hangeul_static/css/nanum-square-neo.css" rel="stylesheet">
    <!-- CSS only -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/joolmag.css' %}"/>
    <!--google icon-->
    <script src="https://kit.fontawesome.com/2f3227cf14.js" crossorigin="anonymous"></script>
    <!--js-->
    <script defer="defer" src="{% static 'js/main.js' %}"></script>
  </head>

  {% if user.is_authenticated %}

    <body class="mainbg">
      <div class="sterun-logo-m">
        <a href={% url "index" %}>
          <img src="{% static "img/index_logo.png" %}" alt="logo-top" height="auto" ,="," width="200px">
        </a>
      </div>
      <div class="run-submit-title">
        <div>
          {% if category == "10K" %}
            <div class="sub-title">10Km-
            </div>
          {% elif category == "HM" %}
            <div class="sub-title">하프마라톤-
            </div>
          {% elif category == "FM" %}
            <div class="sub-title">풀마라톤-
            </div>
          {% endif %}
        </div>
        <div class="sub-title">PB 입력하기</div>
      </div>
      <div class="run-submit-prev">
        <div class="previous-btn">
          <a href="{{ request.META.HTTP_REFERER }}">
            <img src="{% static "img/circle-arrow-down.png" %}" alt="logo-top" height="50px" ,="," width="auto"></a>
        </div>
      </div>
      <div class="run-form-container">
        <form method="post" id="contactForm" class="run-sm-form" name="contactForm" action="{% url 'runres:pbRes' user.pk category %}" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-control">
            <div class="form-label">대회명
            </div><input class="run-input" id="title" name="title" placeholder="대회명을 입력해 주세요" type="text" required="required"/>
          </div>
          <div class="form-control">
            <div class="form-label">날짜
            </div><input class="run-input" type="date" name="date" required="required" id="record_date">
          </div>
          <div class="form-control">
            <div class="form-label">기록증
            </div><input class="run-input" type="file" name="image" required="required" id="image">
          </div>
          <div class="form-control">
            <div class="form-label">기록
            </div>
            <div class="ms-row">
              <input class="run-input-t" type="number" name="time_h" id="time_h">
              <div class="ms-txt">시간</div>
              <input class="run-input-t" type="number" name="time_m" required="required" id="time_m">
              <div class="ms-txt">분</div>
              <input class="run-input-t" type="number" name="time_s" required="required" id="time_s">
              <div class="ms-txt">초</div>
            </div>
          </div>
          <div class="form-control">
            <div class="form-label">메모
            </div>
            <textarea class="run-input" id="inputMessage" name="desc" placeholder="메모를 입력해 주세요" data-parsley-pattern="^[a-zA-Z0-9\s.:,!?']+$"></textarea>
          </div>
          <div class="btn-control">
            <button type="submit" name="submit" id="submit-form-btn" class="submit-btn">
              <p class="btn-text">등록하기</p>
              <span class="spinner-login"></span>
            </button>
          </div>
        </div>
      </form>

      <script>
        const btn = document.getElementById('submit-form-btn');
        const form = document.getElementById('contactForm');
        btn.addEventListener('click', () => {
          if (form.checkValidity()) {
            btn
              .classList
              .add('loading-login'); // 브라우저 기본 alert도 출력
          }
          // 로그인 처리 시뮬레이션 (예: 2초 후 완료)
          setTimeout(() => {
            btn
              .classList
              .remove('loading-login');
          }, 20000);
        });
      </script>
    </body>
  {% else %}

    <body class="login-page">
      <div class="login-container">
        <div class="login-page-top-margin"></div>
        <div class="j-navbar-brand">
          <a href="{% url 'index' %}">
            <img src="{% static "img/logo2@.png" %}" alt="logo-top" height="auto," width="auto">
          </a>
        </div>
        <div>
          <div class="login-container">
            <form method="post" action="{% url 'users:login' %}" class="form-container">
              {% csrf_token %}
              {% include "users/form_errors.html" %}
              <div>
                <input type="text" name="username" id="username" class="id" placeholder="아이디">
              </div>
              <div>
                <input type="text" name="password" id="password" class="pw" placeholder="비밀번호">
              </div>
              <div>
                <button type="submit" class="login-submit">로그인</button>
              </div>
              <a href="{% url 'users:signup' %}">
                <span class="signup-btn">회원가입</span></a>
            </form>
          </div>
        </div>
      </div>
    </body>
  {% endif %}

</html>

templates/pb/run_pb_update.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">

  <head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
    <meta name="description" content="sterun"/>
    <meta name="keywords" content="sterun"/>
    <title>STERUN</title>
    <link rel="shortcut icon" href="#"/>
    <!-- FONT -->
    <style>
      @import url("https://fonts.googleapis.com/css2?family=Rubik+Glitch&display=swap");
      @import url("https://fonts.googleapis.com/css2?family=Tektur:wght@500;600&display=swap");
      @import url("https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@200;400;600&display=swap");
    </style>
    <link href="https://hangeul.pstatic.net/hangeul_static/css/nanum-square-neo.css" rel="stylesheet">
    <!-- CSS only -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/joolmag.css' %}"/>
    <!--google icon-->
    <script src="https://kit.fontawesome.com/2f3227cf14.js" crossorigin="anonymous"></script>
    <!--js-->
    <script defer="defer" src="{% static 'js/main.js' %}"></script>
  </head>

  {% if user.is_authenticated %}

    <body class="mainbg">
      <div class="sterun-logo-m">
        <a href={% url "index" %}>
          <img src="{% static "img/index_logo.png" %}" alt="logo-top" height="auto" ,="," width="200px">
        </a>
      </div>
      <div class="run-submit-title">
        <div>
          <div class="sub-title">{{ record.get_category_display }}
            -
          </div>
        </div>
        <div class="sub-title">PB 갱신하기</div>
      </div>
      <div class="container-400">
        <div class="run-submit-prev">
          <div class="previous-btn">
            <a href="{{ request.META.HTTP_REFERER }}">
              <img src="{% static "img/circle-arrow-down.png" %}" alt="logo-top" height="50px" ,="," width="auto"></a>
          </div>
        </div>
      </div>
      <div class="run-form-container">
        <form method="post" id="contactForm" class="run-sm-form" name="contactForm" action="{% url 'runres:pbUpdate' user.pk record.category %}" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-control">
            <div class="form-label">대회명
            </div><input class="run-input" id="title" name="title" placeholder="새로운 대회명을 입력해 주세요" type="text" required="required"/>
          </div>
          <div class="form-control">
            <div class="form-label">날짜
            </div><input class="run-input" type="date" name="date" required="required" id="record_date">
          </div>
          <div class="form-control">
            <div class="form-label">기록증
            </div><input class="run-input" type="file" name="image" required="required" id="image">
          </div>
          <div class="form-control">
            <div class="form-label">기록
            </div>
            <div class="ms-row">
              <input class="run-input-t" type="number" name="time_h" id="time_h">
              <div class="ms-txt">시</div>
              <input class="run-input-t" type="number" name="time_m" required="required" id="time_m">
              <div class="ms-txt">분</div>
              <input class="run-input-t" type="number" name="time_s" required="required" id="time_s">
              <div class="ms-txt">초</div>
            </div>
          </div>
          <div class="form-control">
            <div class="form-label">메모
            </div>
            <textarea class="run-input" id="inputMessage" name="desc" placeholder="메모를 입력해 주세요" data-parsley-pattern="^[a-zA-Z0-9\s.:,!?']+$"></textarea>
          </div>
          <!--div class="btn-control"> <button type="submit" name="submit" id="submit-form-btn" class="submit-btn"> Submit </button> </div-->
          <div class="btn-control">
            <button type="submit" name="submit" id="submit-form-btn" class="submit-btn">
              <p class="btn-text">등록하기</p>
              <span class="spinner-login"></span>
            </button>
          </div>
        </form>

        <script>
          const btn = document.getElementById('submit-form-btn');
          const form = document.getElementById('contactForm');
          btn.addEventListener('click', () => {
            if (form.checkValidity()) {
              btn
                .classList
                .add('loading-login'); // 브라우저 기본 alert도 출력
            }
            // 로그인 처리 시뮬레이션 (예: 2초 후 완료)
            setTimeout(() => {
              btn
                .classList
                .remove('loading-login');
            }, 20000);
          });
        </script>
      </body>
    {% else %}

      <body class="login-page">
        <div class="login-container">
          <div class="login-page-top-margin"></div>
          <div class="j-navbar-brand">
            <a href="{% url 'index' %}">
              <img src="{% static "img/logo2@.png" %}" alt="logo-top" height="auto," width="auto">
            </a>
          </div>
          <div>
            <div class="login-container">
              <form method="post" action="{% url 'users:login' %}" class="form-container">
                {% csrf_token %}
                {% include "users/form_errors.html" %}
                <div>
                  <input type="text" name="username" id="username" class="id" placeholder="아이디">
                </div>
                <div>
                  <input type="text" name="password" id="password" class="pw" placeholder="비밀번호">
                </div>
                <div>
                  <button type="submit" class="login-submit">로그인</button>
                </div>
                <a href="{% url 'users:signup' %}">
                  <span class="signup-btn">회원가입</span></a>
              </form>
            </div>
          </div>
        </div>
      </body>
    {% endif %}

  </html>