article/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'article'
urlpatterns = [
    path("", views.index, name="article"),
    path("<int:article_id>/", views.article, name="article"),
    path("search/", views.search, name="search"),
    path("alldata/", views.alldata, name="alldata"),
    path("searchtitle/", views.searchTitle, name='searchtitle'),
    path("articleres/", views.articleRes, name='articleres'),
    path("articleresfunc/", views.articleResFunc, name='articleresfunc'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bingo/urls.py
from django.urls import path

from . import views

app_name = "bingo"

urlpatterns = [
    path("<str:pk>", views.bingo, name="bingo"),
    path("createbingo/<str:pk>", views.create_bingo, name="create_bingo"),
    path("update-public-status/<str:pk>", views.update_public_status, name="update_public_status"),
    path("bingoupdate/<str:pk>", views.bingoupdate, name="bingoupdate"),
    path("bingores/<str:pk>", views.bingores, name="bingores"),
    path("bingoreset/", views.bingoreset, name="bingoreset"),
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path('go-back/', views.go_back_view, name='go_back'),
    path('setting/', views.setting_page, name='setting_page'),
]

record/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = "runres"

urlpatterns = [
    path("resister/", views.runres, name="runres"),
    path('recordres/', views.recordres, name='recordres'),
    path('recordview/<str:pk>/', views.recordview, name='recordview'),
    path('recordUpdateView/<str:pk>/<str:record_id>', views.recordUpdateView, name='recordUpdateView'),
    path('recordUpdate/<str:pk>/<str:record_id>', views.recordUpdate, name='recordUpdate'),
    path('recordrank/', views.recordRank, name="recordRank"),
    path('recordCheck/', views.recordCheck, name="recordCheck"),
    path('recordConfirm/<str:id>', views.recordConfirm, name="recordConfirm"),
    path('recordReject/<str:id>', views.recordReject, name="recordReject"),
    path('recordDelete/<str:id>', views.recordDelete, name="recordDelete"),
    path('pbrank/', views.pbRank, name="pbRank"),
    path('pbview/<str:pk>/', views.pbView, name="pbView"),
    path('pbresPage/<str:pk>/<str:category>/', views.pbresPage, name="pbresPage"),
    path('pbRes/<str:pk>/<str:category>/', views.pbRes, name="pbRes"),
    path('pbUpdateView/<str:pk>/<str:category>/', views.pbUpdateView, name="pbUpdateView"),
    path('pbUpdate/<str:pk>/<str:category>/', views.pbUpdate, name="pbUpdate"),
    path('runPbCheck/', views.runPbCheck, name="runPbCheck"),
    path('pbConfirm/<str:id>', views.pbConfirm, name="pbConfirm"),
    path('pbReject/<str:id>', views.pbReject, name="pbReject"),
    path('pbDelete/<str:id>', views.pbDelete, name="pbDelete"),
    path('teamassign/', views.team_assign_view, name="team_assign_view"),
    path("teams/assign/save/", views.save_team_members, name="save_team_members"),
]

steruncomm/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path('users/', include('users.urls')),
    path("attendance/", include("attendance.urls")),
    path("runres/", include("record.urls")),
    path("bingo/", include("bingo.urls")),
    path("article/", include("article.urls")),
    path("marathon/", include("marathon.urls")),
    path('summernote/', include('django_summernote.urls')),  # summernote URL 추가
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import *

app_name = "users"
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name = "users/login.html"), name = "login"),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

  <head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
    <meta name="description" content="STERUN"/>
    <meta name="keywords" content="STERUN"/>
    <title>STERUN</title>
    <link rel="shortcut icon" href='{% static "img/favicon.png" %}'/>
    <!-- FONT -->
    <style>
      @import url("https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@200;400;600&display=swap");
    </style>
    <link href="https://hangeul.pstatic.net/hangeul_static/css/nanum-square-neo.css" rel="stylesheet">
    <!-- CSS only -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/joolmag.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/article.css' %}"/>
    <!--google icon-->
    <script src="https://kit.fontawesome.com/2f3227cf14.js" crossorigin="anonymous"></script>
    <!--js-->
    <script defer="defer" src="{% static 'js/main.js' %}"></script>
    <!--jquery-->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://t1.kakaocdn.net/kakao_js_sdk/2.5.0/kakao.min.js" crossorigin="anonymous"></script>
    <script>
      Kakao.init('b1937e5c9e32d1c6b3aae0983529600b');
    </script>
  </head>

  <body id="content" class="mainbg">
    <div class="main-view">
      <!-- 로딩 화면 -->
      <div class="mask">
        <img class="loadingImg" src="{% static 'img/Blocks@1x-1.0s-200px-200px.gif' %}" alt="" height="100px;" width="100px;">
      </div>
      <!-- 로딩화면 끝 -->
      <div class="info-container">
        <div class="sterun-logo-m">
          <a href={% url "index" %}>
            <img src="{% static "img/index_logo.png" %}" alt="logo-top" height="auto" width="auto">
          </a>
        </div>
        <div class="j-nav-items fade-in-up-short1">
          <div class="j-nav-item">
            <a href="{% url 'index' %}">스트런</a>
          </div>
          <div class="j-nav-item">
            <a href="{% url 'article:article' %}">공지</a>
          </div>
          <div class="j-nav-item">
            {% if user.is_authenticated %}
              <a href="{% url 'marathon:marathon_list' %}">마라톤</a>
            {% else %}
              <a href="{% url 'users:login' %}">마라톤</a>
            {% endif %}
          </div>
          <div class="j-nav-item">
            {% if user.is_authenticated %}
              <a href="{% url 'bingo:bingo' request.user.pk %}">빙고</a>
            {% else %}
              <a href="{% url 'users:login' %}">빙고</a>
            {% endif %}
          </div>
          <div class="j-nav-item">
            {% if user.is_authenticated %}
              <a href="{% url 'runres:recordRank' %}">마일리지</a>
            {% else %}
              <a href="{% url 'users:login' %}">마일리지</a>
            {% endif %}
          </div>
          <div class="j-nav-item">
            {% if user.is_authenticated %}
              <a href="{% url 'runres:pbRank' %}">PB</a>
            {% else %}
              <a href="{% url 'users:login' %}">PB</a>
            {% endif %}
          </div>
          {% if user.is_staff %}
            <div class="j-nav-item">
              <a href="{% url 'setting_page' %}">관리</a>
            </div>
          {% endif %}
        </div>
        <div class="login-sns-box">

          <div class="info-icons">
            <div class="info-icon">
              <i class="fa-regular fa-envelope"></i>
            </div>
            <div class="info-icon">
              <a href="https://www.instagram.com/hyunwoo_05/" target="_blank">
                <i class="fa-brands fa-instagram"></i>
              </a>
            </div>
            <div class="info-icon">
              <i class="fa-brands fa-youtube"></i>
            </div>
          </div>
          <div class="login-box">
            {% if user.is_authenticated %}
              <a href="{% url 'users:logout' %}">
                <div class="login-btn">{{ request.user.username }}
                  님 로그아웃</div>
              </a>
            {% else %}
              <a href="{% url 'users:login' %}">
                <div class="login-btn">로그인</div>
              </a>
              <a href="{% url 'users:signup' %}">
                <div class="login-btn">회원가입</div>
              </a>
            {% endif %}
          </div>
        </div>
      </div>

      {% block content %}{% endblock content %}

      <script>
        $(document).ready(function () {
          $("select[name=month]").val("{{ month }}");
          $("select[name=month]").change(function () {
            $("#month-filter").submit();
          });
        });
        $(document).ready(function () {
          $("select[name=team]").val("{{ team }}");
          $("select[name=team]").change(function () {
            $("#team-filter").submit();
          });
        });
      </script>

      <div class="nav-mobile">
        <a class="flex-gw1" href="{% url 'index' %}">
          <div class="nav-item-mobile">
            <div class="menu-icon-mobile">
              <img src="{% static 'img/home-white.png' %}" alt="" height="25px" width="25px">
            </div>
            <div class="menu-title-mobile">홈</div>
          </div>
        </a>
        <a class="flex-gw1" href="{% url 'article:article' %}">
          <div class="nav-item-mobile">
            <div class="menu-icon-mobile">
              {% if request.resolver_match.url_name == 'article' %}
                <img src="{% static 'img/doc-fill.png' %}" alt="" height="25px" width="25px">
              {% else %}
                <img src="{% static 'img/doc.png' %}" alt="" height="25px" width="25px">
              {% endif %}
            </div>
            <div class="menu-title-mobile">공지</div>
          </div>
        </a>
        {% if user.is_authenticated %}
          <a class="flex-gw1" href="{% url 'bingo:bingo' user.pk %}">
            <div class="nav-item-mobile">
              <div class="menu-icon-mobile">
                {% if request.resolver_match.url_name == 'bingo' %}
                  <img src="{% static 'img/puzzle-black.png' %}" alt="" height="25px" width="25px">
                {% else %}
                  <img src="{% static 'img/puzzle-white.png' %}" alt="" height="25px" width="25px">
                {% endif %}
              </div>
              <div class="menu-title-mobile">빙고</div>
            </div>
          </a>
        {% else %}
          <a class="flex-gw1" href="{% url 'users:login' %}">
            <div class="nav-item-mobile">
              <div class="menu-icon-mobile">
                {% if request.resolver_match.url_name == 'bingo' %}
                  <img src="{% static 'img/puzzle-black.png' %}" alt="" height="25px" width="25px">
                {% else %}
                  <img src="{% static 'img/puzzle-white.png' %}" alt="" height="25px" width="25px">
                {% endif %}
              </div>
              <div class="menu-title-mobile">빙고</div>
            </div>
          </a>
        {% endif %}
        {% if user.is_authenticated %}
          <a class="flex-gw1" href="{% url 'runres:recordRank' %}">
            <div class="nav-item-mobile">
              <div class="menu-icon-mobile">
                {% if request.resolver_match.url_name == 'recordview' %}
                  <img src="{% static 'img/trophy-black.png' %}" alt="" height="25px" width="25px">
                {% else %}
                  <img src="{% static 'img/trophy-white.png' %}" alt="" height="25px" width="25px">
                {% endif %}
              </div>
              <div class="menu-title-mobile">마일리지</div>
            </div>
          </a>
        {% else %}
          <a class="flex-gw1" href="{% url 'users:login' %}">
            <div class="nav-item-mobile">
              <div class="menu-icon-mobile">
                {% if request.resolver_match.url_name == 'recordview' %}
                  <img src="{% static 'img/trophy-black.png' %}" alt="" height="25px" width="25px">
                {% else %}
                  <img src="{% static 'img/trophy-white.png' %}" alt="" height="25px" width="25px">
                {% endif %}
              </div>
              <div class="menu-title-mobile">마일리지</div>
            </div>
          </a>
        {% endif %}
        {% if user.is_authenticated %}
          <a class="flex-gw1" href="{% url 'runres:pbRank' %}">
            <div class="nav-item-mobile">
              <div class="menu-icon-mobile">
                {% if request.resolver_match.url_name == 'pbRank' %}
                  <img src="{% static 'img/diamond-filled.png' %}" alt="" height="25px" width="25px">
                {% else %}
                  <img src="{% static 'img/diamond.png' %}" alt="" height="25px" width="25px">
                {% endif %}
              </div>
              <div class="menu-title-mobile">PB</div>
            </div>
          </a>
        {% else %}
          <a class="flex-gw1" href="{% url 'users:login' %}">
            <div class="nav-item-mobile">
              <div class="menu-icon-mobile">
                {% if request.resolver_match.url_name == 'pbRank' %}
                  <img src="{% static 'img/diamond-filled.png' %}" alt="" height="25px" width="25px">
                {% else %}
                  <img src="{% static 'img/diamond.png' %}" alt="" height="25px" width="25px">
                {% endif %}
              </div>
              <div class="menu-title-mobile">PB</div>
            </div>
          </a>
        {% endif %}
        {% if user.is_authenticated %}
          <a class="flex-gw1" href="{% url 'marathon:marathon_list' %}">
            <div class="nav-item-mobile">
              <div class="menu-icon-mobile">
                {% if request.resolver_match.url_name == 'marathon_list' %}
                  <img src="{% static 'img/finish-line-fill.png' %}" alt="" height="25px" width="25px">
                {% else %}
                  <img src="{% static 'img/finish-line.png' %}" alt="" height="25px" width="25px">
                {% endif %}
              </div>
              <div class="menu-title-mobile">마라톤</div>
            </div>
          </a>
        {% else %}
          <a class="flex-gw1" href="{% url 'users:login' %}">
            <div class="nav-item-mobile">
              <div class="menu-icon-mobile">
                {% if request.resolver_match.url_name == 'marathon_list' %}
                  <img src="{% static 'img/finish-line-fill.png' %}" alt="" height="25px" width="25px">
                {% else %}
                  <img src="{% static 'img/finish-line.png' %}" alt="" height="25px" width="25px">
                {% endif %}
              </div>
              <div class="menu-title-mobile">마라톤</div>
            </div>
          </a>
        {% endif %}
      </div>
    </div>
  </body>
  <footer>
    <div class="rights">
      <p>© JOOL CO., LTD. All Rights Reserved.</p>
    </div>
  </footer>

</html>

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

  <head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
    <meta name="description" content="STERUN"/>
    <meta name="keywords" content="STERUN"/>
    <title>STERUN</title>
    <link rel="shortcut icon" href='{% static "img/favicon.png" %}'/>
    <!-- FONT -->
    <style>
      @import url("https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@200;400;600&display=swap");
    </style>
    <link href="https://hangeul.pstatic.net/hangeul_static/css/nanum-square-neo.css" rel="stylesheet">
    <!-- CSS only -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/joolmag.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}"/>
    <!--google icon-->
    <script src="https://kit.fontawesome.com/2f3227cf14.js" crossorigin="anonymous"></script>
    <!--js-->
    <script defer="defer" src="{% static 'js/main.js' %}"></script>
  </head>

  <body class="mainbg">
    <div class="info-container">
      <div class="info-icons">
        <div class="info-icon">
          <i class="fa-regular fa-envelope"></i>
        </div>
        <div class="info-icon">
          <a href="https://www.instagram.com/hyunwoo_05/" target="_blank">
            <i class="fa-brands fa-instagram"></i>
          </a>
        </div>
        <div class="info-icon">
          <i class="fa-brands fa-youtube"></i>
        </div>
      </div>
      <div class="login-box">
        {% if user.is_authenticated %}
          <a href="{% url 'users:logout' %}">
            <div class="login-btn">{{ user.username }}
              님 로그아웃</div>
          </a>
        {% else %}
          <a href="{% url 'users:login' %}">
            <div class="login-btn">LOGIN</div>
          </a>
          <a href="{% url 'users:signup' %}">
            <div class="login-btn">SIGN-UP</div>
          </a>
        {% endif %}
      </div>
    </div>
    <div class="j-nav-container">
      <div class="j-navbar-brand fade-in-up-3">
        <a href="">
          <img src="{% static "img/index_logo.png" %}" alt="logo-top" height="auto" width="500px">
        </a>
      </div>
      <div class="j-nav-items fade-in-up-5">
        <div class="j-nav-item">
          <a href="{% url 'index' %}">스트런</a>
        </div>
        <div class="j-nav-item">
          <a href="{% url 'article:article' %}">공지</a>
        </div>
        <div class="j-nav-item">
          {% if user.is_authenticated %}
            <a href="{% url 'marathon:marathon_list' %}">마라톤</a>
          {% else %}
            <a href="{% url 'users:login' %}">마라톤</a>
          {% endif %}
        </div>
        <div class="j-nav-item">
          {% if user.is_authenticated %}
            <a href="{% url 'bingo:bingo' user.pk %}">빙고</a>
          {% else %}
            <a href="{% url 'users:login' %}">빙고</a>
          {% endif %}
        </div>
        <div class="j-nav-item">
          {% if user.is_authenticated %}
            <a href="{% url 'runres:recordRank' %}">마일리지</a>
          {% else %}
            <a href="{% url 'users:login' %}">마일리지</a>
          {% endif %}
        </div>
        <div class="j-nav-item">
          {% if user.is_authenticated %}
            <a href="{% url 'runres:pbRank' %}">PB</a>
          {% else %}
            <a href="{% url 'users:login' %}">PB</a>
          {% endif %}
        </div>
        {% if user.is_staff %}
          <div class="j-nav-item">
            <a href="{% url 'setting_page' %}">관리</a>
          </div>
        {% endif %}
      </div>
      <div class="main-img-container">
        <img class="main-img fade-in-up-7" src="{% static "img/index_main.jpg" %}" alt="main-img" height="auto," width="auto">
      </div>
      <div class="login-box-mobile">
        {% if user.is_authenticated %}
          <a href="{% url 'users:logout' %}">
            <div class="login-btn-mobile">{{ user.username }}
              님 로그아웃</div>
          </a>
        {% else %}
          <a href="{% url 'users:login' %}">
            <div class="login-btn-mobile">로그인</div>
          </a>
          <a href="{% url 'users:signup' %}">
            <div class="login-btn-mobile">회원가입</div>
          </a>
        {% endif %}
      </div>
      <div class="rights">
        <p>© JOOL CO., LTD. All Rights Reserved.</p>
      </div>
      {% if user.is_authenticated %}
        <div class="nav-mobile">
          <a class="flex-gw1" href="{% url 'index' %}">
            <div class="nav-item-mobile">
              <div class="menu-icon-mobile">
                <img src="{% static 'img/home-black.png' %}" alt="" height="25px" width="25px">
              </div>
              <div class="menu-title-mobile">홈</div>
            </div>
          </a>
          <a class="flex-gw1" href="{% url 'article:article' %}">
            <div class="nav-item-mobile">
              <div class="menu-icon-mobile">
                <img src="{% static 'img/doc.png' %}" alt="" height="25px" width="25px">
              </div>
              <div class="menu-title-mobile">공지</div>
            </div>
          </a>
          {% if user.is_authenticated %}
            <a class="flex-gw1" href="{% url 'bingo:bingo' user.pk %}">
              <div class="nav-item-mobile">
                <div class="menu-icon-mobile">
                  {% if request.resolver_match.url_name == 'bingo' %}
                    <img src="{% static 'img/puzzle-black.png' %}" alt="" height="25px" width="25px">
                  {% else %}
                    <img src="{% static 'img/puzzle-white.png' %}" alt="" height="25px" width="25px">
                  {% endif %}
                </div>
                <div class="menu-title-mobile">빙고</div>
              </div>
            </a>
          {% else %}
            <a class="flex-gw1" href="{% url 'users:login' %}">
              <div class="nav-item-mobile">
                <div class="menu-icon-mobile">
                  {% if request.resolver_match.url_name == 'bingo' %}
                    <img src="{% static 'img/Book_check_fill@2x.png' %}" alt="" height="25px" width="25px">
                  {% else %}
                    <img src="{% static 'img/Book_check@2x.png' %}" alt="" height="25px" width="25px">
                  {% endif %}
                </div>
                <div class="menu-title-mobile">빙고</div>
              </div>
            </a>
          {% endif %}
          {% if user.is_authenticated %}
            <a class="flex-gw1" href="{% url 'runres:recordRank' %}">
              <div class="nav-item-mobile">
                <div class="menu-icon-mobile">
                  {% if request.resolver_match.url_name == 'recordview' %}
                    <img src="{% static 'img/trophy-black.png' %}" alt="" height="25px" width="25px">
                  {% else %}
                    <img src="{% static 'img/trophy-white.png' %}" alt="" height="25px" width="25px">
                  {% endif %}
                </div>
                <div class="menu-title-mobile">마일리지</div>
              </div>
            </a>
          {% else %}
            <a class="flex-gw1" href="{% url 'users:login' %}">
              <div class="nav-item-mobile">
                <div class="menu-icon-mobile">
                  {% if request.resolver_match.url_name == 'bingo' %}
                    <img src="{% static 'img/Book_check_fill@2x.png' %}" alt="" height="25px" width="25px">
                  {% else %}
                    <img src="{% static 'img/Book_check@2x.png' %}" alt="" height="25px" width="25px">
                  {% endif %}
                </div>
                <div class="menu-title-mobile">마일리지</div>
              </div>
            </a>
          {% endif %}
          {% if user.is_authenticated %}
            <a class="flex-gw1" href="{% url 'runres:pbRank' %}">
              <div class="nav-item-mobile">
                <div class="menu-icon-mobile">
                  {% if request.resolver_match.url_name == 'pbRank' %}
                    <img src="{% static 'img/diamond-filled.png' %}" alt="" height="25px" width="25px">
                  {% else %}
                    <img src="{% static 'img/diamond.png' %}" alt="" height="25px" width="25px">
                  {% endif %}
                </div>
                <div class="menu-title-mobile">PB</div>
              </div>
            </a>
          {% else %}
            <a class="flex-gw1" href="{% url 'users:login' %}">
              <div class="nav-item-mobile">
                <div class="menu-icon-mobile">
                  {% if request.resolver_match.url_name == 'pbRank' %}
                    <img src="{% static 'img/diamond-filled.png' %}" alt="" height="25px" width="25px">
                  {% else %}
                    <img src="{% static 'img/diamond.png' %}" alt="" height="25px" width="25px">
                  {% endif %}
                </div>
                <div class="menu-title-mobile">PB</div>
              </div>
            </a>
          {% endif %}
          {% if user.is_authenticated %}
            <a class="flex-gw1" href="{% url 'marathon:marathon_list' %}">
              <div class="nav-item-mobile">
                <div class="menu-icon-mobile">
                  {% if request.resolver_match.url_name == 'marathon_list' %}
                    <img src="{% static 'img/finish-line-fill.png' %}" alt="" height="25px" width="25px">
                  {% else %}
                    <img src="{% static 'img/finish-line.png' %}" alt="" height="25px" width="25px">
                  {% endif %}
                </div>
                <div class="menu-title-mobile">마라톤</div>
              </div>
            </a>
          {% else %}
            <a class="flex-gw1" href="{% url 'users:login' %}">
              <div class="nav-item-mobile">
                <div class="menu-icon-mobile">
                  {% if request.resolver_match.url_name == 'marathon_list' %}
                    <img src="{% static 'img/finish-line-fill.png' %}" alt="" height="25px" width="25px">
                  {% else %}
                    <img src="{% static 'img/finish-line.png' %}" alt="" height="25px" width="25px">
                  {% endif %}
                </div>
                <div class="menu-title-mobile">마라톤</div>
              </div>
            </a>
          {% endif %}
        {% endif %}
      </div>
    </div>
  </body>

</html>

templates/record_rank.html
{% extends "base.html" %}
{% load static %}
{% block content %}

  {% csrf_token %}
  <div class="space-h30"></div>
  {% if month == "0" or month == None %}
    {% if team != None and team != "0" %}
      <div class="run-submit-title">
        {{ team }}
        마일리지 랭킹</div>
    {% else %}
      <div class="run-submit-title">
        마일리지 랭킹</div>
    {% endif %}
  {% else %}
    <div class="run-submit-title">{{ month }}월 마일리지 랭킹</div>
  {% endif %}
  <div class="space-h30"></div>
  <div class="rank-container">
    <div class="search-sum">
      <div class="filter-line">
        <div class="filter-card flex-row">
          <form action="{% url 'runres:recordRank' %}" method="get" id="month-filter">
            <select name="month" class="month-filter">
              <option value="0">ALL</option>
              <option value="1">1</option>
              <option value="2">2</option>
              <option value="3">3</option>
              <option value="4">4</option>
              <option value="5">5</option>
              <option value="6">6</option>
              <option value="7">7</option>
              <option value="8">8</option>
              <option value="9">9</option>
              <option value="10">10</option>
              <option value="11">11</option>
              <option value="12">12</option>
            </select>
          </form>
        </div>
        <div class="month-filter-txt">월</div>
        <div class="filter-card flex-row">
          <form action="{% url 'runres:recordRank' %}" method="get" id="team-filter">
            <select name="team" class="month-filter">
              <option value="0">ALL</option>
              {% for team in team_list %}
                <option value="{{ team.team_id }}">{{ team }}</option>
              {% endfor %}
            </select>
          </form>
        </div>
        <div class="month-filter-txt">팀</div>
      </div>
      <div class="distance-sum">총
        {{ distance_sum.distance__sum|floatformat:2 }}
        Km</div>
    </div>
    <div class="space-h10"></div>
    <div class="record-rank-container">
      {% for record in record_rank %}
        <div class="record-col">
          {% if forloop.counter == 1 %}
            <div class="record-row">
              <img src="{% static 'img/01-Gold-Medal.png' %}" alt="hamb-btn" height="40px," width="40px">
              {{ record.user__last_name }}{{ record.user__first_name }}
              :
              {{ record.record_sum | floatformat:2 }}
              km
            </div>
          {% elif forloop.counter == 2 %}
            <div class="record-row">
              <img src="{% static 'img/02-Silver-Medal.png' %}" alt="hamb-btn" height="40px," width="40px">
              {{ record.user__last_name }}{{ record.user__first_name }}
              :
              {{ record.record_sum | floatformat:2 }}
              km
            </div>
          {% elif forloop.counter == 3 %}
            <div class="record-row">
              <img src="{% static 'img/03-Bronze-Medal.png' %}" alt="hamb-btn" height="40px," width="40px">
              {{ record.user__last_name }}{{ record.user__first_name }}
              :
              {{ record.record_sum | floatformat:2 }}
              km
            </div>
          {% elif forloop.counter == 4 %}
            <div class="space-h30"></div>
            <div class="mg-left-10">
              {{ forloop.counter }}.
              {{ record.user__last_name }}{{ record.user__first_name }}
              :
              {{ record.record_sum | floatformat:2 }}
              km
            </div>
          {% else %}
            <div class="mg-left-10">
              {{ forloop.counter }}.
              {{ record.user__last_name }}{{ record.user__first_name }}
              :
              {{ record.record_sum | floatformat:2 }}
              km
            </div>
          {% endif %}
        </div>
      {% endfor %}
    </div>
  </div>
  <div class="btn-control">
    <a href="{% url "runres:recordview" request.user.pk %}">
      <button class="submit-btn">나의 마일리지</button>
    </a>
  </div>
  <script>
    // 페이지가 모두 로드되면 호출
    window.addEventListener('load', function () {
      const loader = document.getElementById('loader');
      const content = document.getElementById('content');
      // 로딩 화면 숨기기
      loader.style.display = 'none';
      // 콘텐츠 보여주기
      content.style.display = 'block';
    });
  </script>

{% endblock content %}